---
title: "Tidy coral example"
author: "Ross Cunning"
date: "3/13/2018"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In this document, I am following along with the NCEAS tutorial that can be found [here](https://nceas.github.io/crescynt-training/tidy_coral).

```{r}
## libraries
library(tidyverse)
library(janitor) # install.packages('janitor')
library(skimr) # install.packages('skimr')
library(stringr) # added when we needed it for benthic data

## data filepaths/urls ----

## benthic data
benthic_url <- 'https://www.nodc.noaa.gov/archive/arc0054/0104255/1.1/data/0-data/cd08/100308OaAla03m.CSV'

## buoy data
buoy_url <- 'http://www.ndbc.noaa.gov/view_text_file.php?filename=mokh1h2010.txt.gz&dir=data/historical/stdmet/'
```

# Benthic data

```{r}
benthic_raw <- read_csv(benthic_url)
head(benthic_raw)
# Column names have capitals, spaces, etc.... we want to rename these columns
names(benthic_raw)
```

```{r}
## the `janitor` package's `clean_names` function
benthic <- benthic_raw %>%
  janitor::clean_names()

names(benthic)
```

```{r}
# Select only columns we are interested in
benthic <- benthic %>%
  select(id_name, point, x, y, id_date)

head(benthic)
```

```{r}
# Don't want the pound signs in the id_date column
benthic <- benthic %>%
  mutate(date = stringr::str_remove_all(id_date, "#"))
head(benthic)
```

```{r}
# Make a plot
ggplot(benthic, aes(x = date, fill = id_name)) +
  geom_bar()
```

# Buoy data

```{r}
buoy_raw <- readr::read_csv(buoy_url)
head(buoy_raw) # hmm this doesn't look right! Why not?
# It is a fixed-width file, sometimes one space and sometimes two separate columns.
# read_table2 allows for this...
## read_table2
buoy_raw <- read_table2(buoy_url)
head(buoy_raw) ## this is what we need!
```

```{r}
buoy <- buoy_raw

## 1. overwrite column names
names(buoy) <- str_c(names(buoy),                  ## current header
                  buoy %>% filter(`#YY` == "#yr"), ## row1 -- don't say buoy[1,] 
                  sep = "_")                       ## separate by `_`

## inspect
names(buoy) ## Looks a lot better


## 2. clean up a bit more to get rid of the `#`s and the `/`s. 
names(buoy) <- str_replace_all(names(buoy), "#", "")  # replace `#` with nothing 
names(buoy) <- str_replace_all(names(buoy), "/", "_") # replace `/` with `_`

## inspect to make sure it worked
names(buoy)

## 3. remove redundant row with units
buoy <- buoy %>%
  filter(YY_yr != "#yr")
```

```{r}
# Barplot of water temperature
ggplot(buoy, aes(WTMP_degC)) +
  geom_bar() +
  theme(axis.text.x = element_text(angle = 90))  # how to rotate tick labels
```

```{r}
# Clearly 999 is not an actual temperature that was observed.
# 999 is frequently used as a missing value code, so we need to convert this to NA
buoy <- buoy %>%
  mutate(WTMP_degC_test = str_replace_all(WTMP_degC, "999.0", ""))

# Barplot of water temperature
ggplot(buoy, aes(WTMP_degC_test)) +
  geom_bar() +
  theme(axis.text.x = element_text(angle = 90))  # how to rotate tick labels
```

# Combine the benthic and the buoy datasets

```{r}
names(buoy)
names(benthic)

# Need a date column in the benthic dataset -- need to unite month, day, year
buoy <- buoy %>%
  unite(date, c(YY_yr, MM_mo, DD_dy), sep = "-")

head(buoy)
```

```{r}
# join datasets
bb_join <- benthic %>%
  left_join(buoy, by = "date")

## let's select a few columns and inspect:
bb_join %>%
  select(id_name, x, y, date, hh_hr, mm_mn, WTMP_degC) %>%
  head()
```

```{r}
# need to get daily mean temperature from the bouy data, then join with benthic
buoy_daily <- buoy %>%
  mutate(temp_clean = as.numeric(gsub("999.0", NA, WTMP_degC))) %>%   # first need to get rid of 999's
  group_by(date) %>%   # then group by date
  summarise(mean_temp = mean(temp_clean, na.rm=T))  # then get mean temperature

buoy_daily
```

```{r}
# now merge mean temps with benthic 
# join datasets
bb_join <- benthic %>%
  left_join(buoy_daily, by = "date")

bb_join
```

